import Head from "next/head";
import { useQueryClient } from "react-query";
import { useSelector, useDispatch } from "react-redux";
import { BiUserPlus } from "react-icons/bi";
import Table from "@/components/table";
import Form from "@/components/form";
import DeleteComponent from "@/components/delete";
import { deleteUser, getUsers } from "@/lib/helper";
import { deleteAction, toggleChangeAction } from "@/redux/reducer";

export default function Home() {
  const queryClient = useQueryClient();
  const visible = useSelector((state) => state.app.client.toggleForm);
  const deleteId = useSelector((state) => state.app.client.deleteId);
  const dispatch = useDispatch();

  const handler = () => {
    dispatch(toggleChangeAction());
  };

  const cancelHandler = async () => {
    await dispatch(deleteAction(null));
  };

  const deleteHandler = async () => {
    if (deleteId) {
      await deleteUser(deleteId);
      await queryClient.prefetchQuery("users", getUsers);
      await dispatch(deleteAction(null));
    }
  };

  return (
    <section>
      <Head>
        <title>Employee Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Employee Management
        </h1>

        <div className="mx-auto flex justify-between py-5 border-b">
          <div className="flex gap-3">
            <button
              onClick={handler}
              className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-indigo-500"
            >
              Add Employee{" "}
              <span className="px-1">
                <BiUserPlus size={23} />
              </span>
            </button>
          </div>
          {deleteId && (
            <DeleteComponent
              deleteHandler={deleteHandler}
              cancelHandler={cancelHandler}
            />
          )}
        </div>
        {visible && <Form />}
        <div className="container mx-auto">
          <Table />
        </div>
      </main>
    </section>
  );
}
